//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanonStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.Bill_details = new HashSet<Bill_details>();
        }

        [DisplayName("Id")]
        public string IdBill { get; set; }
        [DisplayName("Date Created")]
        public System.DateTime Date_Created { get; set; }
        [DisplayName("Customer")]
        public int IdCustomer { get; set; }
        [DisplayName("Emloyee")]
        public int IdEmployee { get; set; }
        [DisplayName("Total")]
        public Nullable<double> Total { get; set; }
        [DisplayName("Status")]
        public Nullable<int> Status { get; set; }
        [DisplayName("Discount")]
        public string Discount_code { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_details> Bill_details { get; set; }
        public virtual Bill_Status Bill_Status { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
