//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanonStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public Nullable<int> Id_Product { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<int> Id_Customer { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Com_txt { get; set; }
        public string Id_Bill { get; set; }
    }
}
