//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanonStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_CanonStoreEntities : DbContext
    {
        public db_CanonStoreEntities()
            : base("name=db_CanonStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accessory> Accessories { get; set; }
        public virtual DbSet<Bill_details> Bill_details { get; set; }
        public virtual DbSet<Bill_Status> Bill_Status { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Product_Types> Product_Types { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    
        public virtual ObjectResult<proc_AVG_star_product_Result> proc_AVG_star_product(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_AVG_star_product_Result>("proc_AVG_star_product", idParameter);
        }
    
        public virtual ObjectResult<proc_sumproductbymonth_Result> proc_sumproductbymonth(Nullable<System.DateTime> datetmp)
        {
            var datetmpParameter = datetmp.HasValue ?
                new ObjectParameter("datetmp", datetmp) :
                new ObjectParameter("datetmp", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_sumproductbymonth_Result>("proc_sumproductbymonth", datetmpParameter);
        }
    
        public virtual ObjectResult<proc_sumsalesbydate_Result> proc_sumsalesbydate(Nullable<System.DateTime> datetmp)
        {
            var datetmpParameter = datetmp.HasValue ?
                new ObjectParameter("datetmp", datetmp) :
                new ObjectParameter("datetmp", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_sumsalesbydate_Result>("proc_sumsalesbydate", datetmpParameter);
        }
    
        public virtual ObjectResult<proc_sumsalesbymonth_Result> proc_sumsalesbymonth(Nullable<System.DateTime> datetmp)
        {
            var datetmpParameter = datetmp.HasValue ?
                new ObjectParameter("datetmp", datetmp) :
                new ObjectParameter("datetmp", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_sumsalesbymonth_Result>("proc_sumsalesbymonth", datetmpParameter);
        }
    
        public virtual ObjectResult<proc_sumsalesbyyear_Result> proc_sumsalesbyyear(Nullable<System.DateTime> datetmp)
        {
            var datetmpParameter = datetmp.HasValue ?
                new ObjectParameter("datetmp", datetmp) :
                new ObjectParameter("datetmp", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_sumsalesbyyear_Result>("proc_sumsalesbyyear", datetmpParameter);
        }
    
        public virtual ObjectResult<proc_Top5bestsellingproduct_Result> proc_Top5bestsellingproduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Top5bestsellingproduct_Result>("proc_Top5bestsellingproduct");
        }
    }
}
