//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanonStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Bill_details = new HashSet<Bill_details>();
        }

        public int Id_product { get; set; }
        [Required]
        [DisplayName("Name")]
        public string Name { get; set; }
        [Required]
        [DisplayName("Brand")]
        public string Brand { get; set; }
        [Required]
        [DisplayName("Price")]
        public Nullable<double> Price { get; set; }
        [Required]
        [DisplayName("Type")]
        public int Type { get; set; }
        [Required]
        [DisplayName("Accesory")]
        public Nullable<int> Acc_Id { get; set; }
        [Required]
        [DisplayName("Warranty")]
        public Nullable<int> Warranty { get; set; }
        [Required]
        [DisplayName("Description")]
        public string Description { get; set; }
        [DisplayName("Image")]
        public string Image { get; set; }
        [DisplayName("Date created")]
        public Nullable<System.DateTime> Date_Created { get; set; }
        [DisplayName("Quantity In Stock")]
        public Nullable<int> Quantity_in_Stock { get; set; }
        [DisplayName("Aperture")]
        public string Aperture { get; set; }
        [DisplayName("Focal Distance")]
        public string Focal_Distance { get; set; }
        [DisplayName("Shutter Speed")]
        public string Shutter_Speed { get; set; }
        public bool Is_Available { get; set; }

        public virtual Accessory Accessory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_details> Bill_details { get; set; }
        public virtual Product_Types Product_Types { get; set; }

        [NotMapped]
        [DisplayName("ImageUpload")]
        public HttpPostedFileBase ImageUpload { get; set; }
    }
}
